spring:
  application:
    name: bankline-api

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://postgres.railway.internal:50724/railway
    username: postgres
    password: DkjXpnYivCUqTosddtXGGOFKEiidZrMR
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          lob:
            non-contextual-creation: true
        show_sql: true
springdoc:
  api-docs:
    path: /api-docs
